M48
; DRILL file {KiCad 8.0.8} date 2025-08-11T17:05:28-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-08-11T17:05:28-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.448
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.500
%
G90
G05
T1
X196.844Y-81.428
T2
X82.6Y-54.2
X82.6Y-149.2
X197.6Y-54.2
X197.6Y-149.2
M30
